name: Notify Slack with Blocks

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Header title for the message'
        required: true
        default: '🔔 Notification'
      message:
        description: 'Message body to send in Slack'
        required: true
        default: 'Hello from GitHub Actions in rich text!'

jobs:
  slack_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send logs to Slack
        env:
          SLACK_WEBHOOK_URL_DEV: ${{ secrets.SLACK_WEBHOOK_URL_DEV }}
          SLACK_WEBHOOK_URL_PRD: ${{ secrets.SLACK_WEBHOOK_URL_PRD }}
        run: |
          if [ "${{ github.event.inputs.environment }}" = "prd01" ]; then
            WEBHOOK_URL="$SLACK_WEBHOOK_URL_PRD"
          else
            WEBHOOK_URL="$SLACK_WEBHOOK_URL_DEV"
          fi
          log_json_lines="log here"
          echo "$WEBHOOK_URL"
          # Send message to slack
          message=$(cat <<EOF
            {
              "text": "*[Tiếng Việt]*\nThông tin log waf\n\n*[English]*\nInfo Log WAF\n\n*[Logs - ${{ github.event.inputs.environment }}]*\n\`\`\`\n${log_json_lines}\n\`\`\`"
            }
          EOF
          )

          echo "Sending message to Slack..."
          curl -X POST -H 'Content-type: application/json' --data "$message" "$WEBHOOK_URL"
