name: Notify Slack with Blocks

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Header title for the message'
        required: true
        default: '🔔 Notification'
      message:
        description: 'Message body to send in Slack'
        required: true
        default: 'Hello from GitHub Actions in rich text!'

jobs:
  slack_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Block-Formatted Slack Message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEV }}
          SLACK_TITLE: ${{ github.event.inputs.title }}
          SLACK_MESSAGE: ${{ github.event.inputs.message }}
        run: |
          jq -n --arg title "$SLACK_TITLE" --arg msg "$SLACK_MESSAGE" '{
            blocks: [
              {
                type: "header",
                text: {
                  type: "plain_text",
                  text: $title,
                  emoji: true
                }
              },
              {
                type: "rich_text",
                elements: [
                  {
                    type: "rich_text_section",
                    elements: [
                      {
                        type: "text",
                        text: $msg
                      }
                    ]
                  }
                ]
              }
            ]
          }' > slack_payload.json

          curl -X POST -H 'Content-type: application/json' \
            --data @slack_payload.json \
            $SLACK_WEBHOOK_URL
