name: Notify Slack Manually

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to send to Slack'
        required: true
        default: 'Hello from GitHub Actions!'

jobs:
  slack_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"${{ github.event.inputs.message }}\"}" \
            $SLACK_WEBHOOK_URL
