name: Toggle EventBridge Scheduler State

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment (e.g., dev01, dev02)"
        required: true
        type: string
      batch_name:
        description: "Batch Rule Name (without prefix)"
        required: true
        type: string
      state:
        description: "Desired state (ENABLED or DISABLED)"
        required: true
        type: choice
        options:
          - ENABLED
          - DISABLED

jobs:
  toggle-scheduler:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::022269452713:role/GitHubActionsAthenaRole
          aws-region: ap-southeast-1

      - name: Set environment variables
        run: |
          echo "SCHEDULER_NAME=td-${{ inputs.env }}-${{ inputs.batch_name }}" >> $GITHUB_ENV
          echo "DESIRED_STATE=${{ inputs.state }}" >> $GITHUB_ENV

      - name: Fetch scheduler info and handle logic
        run: |
          RAW_JSON=$(aws scheduler get-schedule --name "$SCHEDULER_NAME" 2>&1 || true)

          if echo "$RAW_JSON" | grep -q "ResourceNotFoundException"; then
            echo "❌ Scheduler \`$SCHEDULER_NAME\` does not exist." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          SCHEDULER_JSON=$(echo "$RAW_JSON" | jq '.')

          CURRENT_STATE=$(echo "$SCHEDULER_JSON" | jq -r '.State')

          if [ "$CURRENT_STATE" = "$DESIRED_STATE" ]; then
            echo "⚠️ Scheduler is already in desired state: $CURRENT_STATE." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          # Prepare new JSON for update
          JSON_INPUT=$(echo "$SCHEDULER_JSON" | jq --arg state "$DESIRED_STATE" '
            .State = $state
          ')

          aws scheduler update-schedule --cli-input-json "$JSON_INPUT"

          echo "✅ Successfully updated scheduler \`$SCHEDULER_NAME\` to \`$DESIRED_STATE\`." >> $GITHUB_STEP_SUMMARY

      - name: Handle unexpected error
        if: failure()
        run: |
          echo "❌ An unexpected error occurred during the workflow execution." >> $GITHUB_STEP_SUMMARY
