name: WIP_Check active GHAction
on:
  workflow_dispatch:

jobs:
  get-lock-id:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      lock-id-plan: ${{ steps.terraform_plan.outputs.lock_id }}
    steps:
      - name: terraform plan
        id: terraform_plan
        run: |
         echo "Successfully force-unlocked state with ID"
